<meta http-equiv="Content-Type" content="text/html; ">
<meta name="viewport" content="width=device-width">
<title>{% title %}</title>
<link href="https://fonts.googleapis.com/css?family=Lato|Ubuntu%20Mono" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
<link rel="stylesheet" href="https://cdn.eckinox.net/fontawesome/latest/css/fontawesome-all.min.css">
<link rel="stylesheet" href="/asset/nex-model-tools/css/main.css">
<link rel="shortcut icon" href="/favicon.png">
<script src="/asset/extern/jquery-3.3.1.min.js"></script>
<style>{% section "css" %}{% endsection %}</style>
