{% extends "/layout/default" %}

{{ use Eckinox\Nex\form; }}

{% section "header" %}
    <h1><i class="far fa-database" aria-hidden="true"></i>Migrations</h1>
{% endsection %}

{% section "subheader" %}
    CREATE TABLE [ {{= count($create); }} ]
{% endsection %}

{% section "content" %}
    {% form method="post" class="section" %}
        <article class="create message is-dark">
            <div class="message-body">
                {% if $create %}
                    <h2 class="is-size-4 has-text-grey"></h2>

                    <div class="create">
                        {% foreach $create as $model => $item %}
                            <div class="box" style="line-height:1.5em;">
                                <label class="tablename item checkbox">{{= form::checkbox('create[]', $model, true)}} <span>{{= $item }}</span></label>
                                <pre class="has-background-white-ter">{{= $this->_migrations()->table_create($model); }}</pre>
                            </div>
                        {% endforeach %}

                        <button class="button" type="submit">
                            Proceed
                        </button>
                    </div>
                {% else %}
                    <div class="has-text-grey-light">Nothing to create</div>
                {% endif %}
            </div>
        </article>
    {% endform %}

    <div class="is-grouped">
        <a href="{{= $this->url('!/migrate/alter') }}" class="button is-info" type="submit">Next</a>
    </div>
{% endsection %}
