{% extends "/layout/default" %}

{{ use Eckinox\Nex\form; }}

{% section "header" %}
    <h1><i class="far fa-database" aria-hidden="true"></i>Migrations</h1>
{% endsection %}

{% section "subheader" %}
    INDEXES & KEYS [ {{= count($relation ?? []); }} ]
{% endsection %}

{% section "content" %}
    {% form method="post" class="section" %}
        <article class="alter message is-light">
            <div class="message-body">
                {% if $relation ?? false %}
                    <h2 class="is-size-4 has-text-grey">Adding {{= count($relation) }} relation(s)</h2>

                    <button class="button is-danger" type="submit">
                        Proceed
                    </button>
                {% else %}
                    <div class="has-text-grey-light">No index / key to add</div>
                {% endif %}
            </div>
        </article>
    {% endform %}

    <div class="is-grouped">
        <a href="{{= $this->url('!/migrate/alter') }}" class="button is-info" type="submit">Previous</a>
    </div>
{% endsection %}
